### ISSUE TITLE
Compare G-Prop with Deep-G-Prop re number of evaluations

### ISSUE THREAD

**Issue by JJ** [JJ/2021-cec-deep-g-prop#13]
I don't know if that's in the original paper, maybe @pacastillo remembers or at least the parameters used.
The results published by @lulivi are essentially for 200 evaluations (20 individuals by 10 generations). It takes a few minutes in my computer, BTW, so we could really boost this up by multiplying it by a lot.

**Comment by pacastillo** [comment]
I remember that in easy problems, a small number of generations were enough. But to solve more complex problems, a number around 100 generations was neccesary.

**Comment by pacastillo** [comment]
Indeed, in the IEEE TNN paper, we used 50, 100, 500 1000 generations along 50, 100, 500, 1000 training epochs

**Comment by JJ** [comment]
How many repetitions?
