### ISSUE TITLE
Clarify what happens during the crossover if two NN has different number of layers

### ISSUE THREAD

**Issue by lulivi** [JJ/2021-cec-deep-g-prop#15]
Answer [the question](https://github.com/JJ/2021-evostar-deep-g-prop/commit/1a16681f6428d81e10870b47fcb3506b6264e424#diff-9d72889a1d07ba65b247b458d354cac606387586a83f3f5b901d8737a08a3c61R147-R153) in the tex.

**Comment by pacastillo** [comment]
As we show many years ago, the networks to be crossed must have the same number of layers.

**Comment by JJ** [comment]
But many years ago, we had only one hidden layer, right?
