### ISSUE TITLE
Justify the numbers used for the layer configuration maybe changing the value

### ISSUE THREAD

**Issue by lulivi** [JJ/2021-cec-deep-g-prop#16]
We would need to rerun the experiment again ([lines](https://github.com/JJ/2021-evostar-deep-g-prop/blob/9a169257caf5f7cebf4b07f240f19a0bd6d85987/deep-g-prop-evostar-2021.tex#L426-L428));

**Comment by JJ** [comment]
OK, fair enough. I have got it running in my computer, we would need to
design the experiments needed.

**Comment by lulivi** [comment]
Cool! How did you fix it?

**Comment by JJ** [comment]
Just by installing a new version of Python using compiler options for `pyenv`. It's in the README file now.
