### ISSUE TITLE
Adapt Algorithm 1 to the specific case

### ISSUE THREAD

**Issue by JJ** [JJ/2021-cec-deep-g-prop#24]
Probably it should be eliminated already, but if it's not, it should state clearly and succinctly (to be expanded in the section)
- Termination conditions (to be clear, I have no idea what they are; I think it's number of generations, but could be other)
- Lines 3 to 5 probably don't apply here. Since the fitness is "noisy", it's almost impossible that the best fitness stays fixed; and it's indeed likely that it might become worse from one generation to the next.
- Clarify what you mean from "best" individuals.
- Clarify what you mean by "worst" individuals. Are you ranking the population?

**Comment by lulivi** [comment]
Do we want to keep the section then? You are referring to [this](https://github.com/JJ/2021-evostar-deep-g-prop/blob/main/deep-g-prop-evostar-2021.tex#L257-L273), right? 
```
The general the algorithm will proceed like the \autoref{alg:ga} shows.

\begin{algorithm}
  \caption{Genetic Algorithm loop}\label{alg:ga}
  \begin{algorithmic}[1]
    \State \textit{evaluate initial population}
    \While{\textit{max fit is less than ideal and there are generations left}}
    \If{\textit{max fit hasn't improved in some generations}}
    \State \textit{Stop algorithm}
    \EndIf
    \State \textit{select the offspring from the best population individuals}
    \State \textit{apply crossover to the offspring}
    \State \textit{apply mutations to the offspring}
    \State \textit{replace the worst population individuals with the modified offspring}
    \EndWhile
  \end{algorithmic}
\end{algorithm}
```
