### ISSUE TITLE
Experiments

### ISSUE THREAD

**Issue by JJ** [JJ/2021-cec-deep-g-prop#6]
In principle we wouldn't need to have more than the ones already made. Once that's written and included, we'll see if we need a few more.

**Comment by pacastillo** [comment]
Instead of including the following citation:     GProp  \cite{g-prop}
please, use the following citations defined in geneura.bib file:    GProp \cite{castilloNC,CastilloNPL}

**Comment by JJ** [comment]
@pacastillo (anonymized, of course).

**Comment by JJ** [comment]
@JJ (if needed)
